# # # # # # # # # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                  _                    
#  ___  __      __   __ _   _   _           _ __     __ _    __ _  | |__     __ _   _ __ 
# / __| \ \ /\ / /  / _` | | | | |  _____  | '_ \   / _` |  / _` | | '_ \   / _` | | '__|
# \__ \  \ V  V /  | (_| | | |_| | |_____| | | | | | (_| | | (_| | | |_) | | (_| | | |   
# |___/   \_/\_/    \__,_|  \__, |         |_| |_|  \__,_|  \__, | |_.__/   \__,_| |_|   
#                           |___/                           |___/                        
# # # # # # # # # # # # #  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#  i3-nagbar replacement
#  (source: https://github.com/rbnis/legacy-dotfiles/blob/dfd6f956f6d00a1012a3a167d947773095dac7fd/.config/sway/config#L228)
set $nagbar System: (1) lock, (2) Suspend, (3) logout, (4) Shutdown, (5) Reboot, (6) UEFI
mode "$nagbar" {
	bindsym 1 exec --no-startup-id $lock, mode "default"
	bindsym 2 exec systemctl suspend, mode "default"
	bindsym 3 exec i3-msg exit
	bindsym 4 exec systemctl poweroff -i, mode "default"
	bindsym 5 exec systemctl reboot, mode "default"
	bindsym 6 exec systemctl reboot --firmware-setup, mode "default"

    # back to normal: Enter or Escape
	bindsym Return mode "default"
	bindsym Escape mode "default"
}
