# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  _   _____                                  _                                   _   
# (_) |___ /  __      __  _ __ ___           | |   __ _   _   _    ___    _   _  | |_ 
# | |   |_ \  \ \ /\ / / | '_ ` _ \   _____  | |  / _` | | | | |  / _ \  | | | | | __|
# | |  ___) |  \ V  V /  | | | | | | |_____| | | | (_| | | |_| | | (_) | | |_| | | |_ 
# |_| |____/    \_/\_/   |_| |_| |_|         |_|  \__,_|  \__, |  \___/   \__,_|  \__|
#                                                         |___/                       
#														 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# set the default workspace layout
workspace_layout tabbed

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.  set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# resize window (you can also use the mouse for that)
mode "resize" {
	# These bindings trigger as soon as you enter the resize mode

    # Pressing left will shrink the window’s width.
    # Pressing right will grow the window’s width.
    # Pressing up will shrink the window’s height.
    # Pressing down will grow the window’s height.
    bindsym j resize shrink width 10 px or 10 ppt
    bindsym k resize grow height 10 px or 10 ppt
    bindsym l resize shrink height 10 px or 10 ppt
    bindsym semicolon resize grow width 10 px or 10 ppt

    # same bindings, but for the arrow keys
    bindsym Left resize shrink width 10 px or 10 ppt
    bindsym Down resize grow height 10 px or 10 ppt
    bindsym Up resize shrink height 10 px or 10 ppt
    bindsym Right resize grow width 10 px or 10 ppt

    # back to normal: Enter or Escape or $mod+r
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}

# move tiling windows via drag & drop by left-clicking into the title bar,
# or left-clicking anywhere into the window while holding the floating modifier.
tiling_drag modifier titlebar
